package dev.reveryy.revnet.enums;

public enum NetError {
    OK,
    NET_NOT_FOUND,
    DEVICE_NOT_FOUND,
    NET_CONFLICT,
    DEVICE_CONFLICT,
    DEVICE_NET_CONFLICT,
    DEVICE_NET_NOT_FOUND,
    DEVICE_PING_FAILURE,
    DEVICE_PING_SUCCESS,
    INVALID_IP,
    IP_CONFLICT,
    IP_OUT_OF_RANGE,
    INVALID_CIDR,
    CIDR_OUT_OF_RANGE,
    PARENT_NOT_FOUND,
    SUBNET_OUTSIDE_PARENT,
    SUBNET_CONFLICT,
    ROUTER_CONFLICT,
    ROUTER_NOT_FOUND
}
